"""Constants - app/core/constants.py"""

# Audit actions
AUDIT_CREATE = "CREATE"
AUDIT_READ = "READ"
AUDIT_UPDATE = "UPDATE"
AUDIT_DELETE = "DELETE"
AUDIT_LOGIN = "LOGIN"
AUDIT_LOGOUT = "LOGOUT"
AUDIT_VERIFY_EMAIL = "VERIFY_EMAIL"

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
